[project]
name = "odoo-addons-oca-payroll"
version = "18.0.20250330.0"
dependencies = [
    "odoo-addon-payroll==18.0.*",
    "odoo-addon-payroll_account==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
